name: S3 to RDS Workflow

on:
  push:
    branches:
      - main

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest  # Ubuntu 환경에서 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install boto3 mysql-connector-python

      - name: Execute Local SQL Script
        env:
          LOCALSQL_SCRIPT: "C:/Users/User/Desktop/AWS/localsql.py"
        run: |
          echo "Running localsql.py to dump data..."
          python "${LOCALSQL_SCRIPT}"
          echo "localsql.py execution completed successfully!"

      - name: Run SQL Dump and Upload to S3
        env:
          LOCAL_DB_HOST: ${{ secrets.LOCAL_DB_HOST }}
          LOCAL_DB_USER: ${{ secrets.LOCAL_DB_USER }}
          LOCAL_DB_PASSWORD: ${{ secrets.LOCAL_DB_PASSWORD }}
          LOCAL_DB_NAME: ${{ secrets.LOCAL_DB_NAME }}
          TABLE_NAME: ${{ secrets.TABLE_NAME }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_DIRECTORY: "sql_backups/"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: python preprocess.py

  import-to-rds:
    runs-on: ubuntu-latest  # RDS로 Import 실행
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run SQL Download and Import to RDS
        env:
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          S3_DIRECTORY: "sql_backups/"
          RDS_HOST: ${{ secrets.RDS_HOST }}
          RDS_USERNAME: ${{ secrets.RDS_USERNAME }}
          RDS_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          RDS_DATABASE: ${{ secrets.RDS_DATABASE }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: python app.py
